version: "3.9"

services:
  jupyterlab:
    image: jupyter-example-proxy
    build:
      context: "."
      dockerfile: setup/Dockerfile
    container_name: jupyter-example-proxy
    restart: always
    ports:
      - 8888:8888
    environment:
      WORKBENCH_APP_ENABLED: 'true'
      # WORKBENCH_APP_ENABLED: 'false'
    volumes:
      - "${PWD}:/home/jovyan/jupyter-example-proxy"
 